create table Users
(
    id    int primary key generated by default as identity,
    name  varchar(50) unique not null,
    email varchar(70) unique not null
);

create table Orders
(
    id     int primary key generated by default as identity,
    name   varchar(50) not null,
    status varchar(10) not null,
    price  int check ( price > 0 ) not null ,
    user_id int references Users(id) on delete cascade
);

insert into Users(name, email) VALUES ('Margarita', 'mar@mail.com');
insert into Users(name, email) VALUES ('Miron', 'miron@gmail.com');
insert into Users(name, email) VALUES ('Alena', 'AV@gmail.com');


insert into Orders(name, status, price, user_id) VALUES ('Juice','SENT',100, 1);
insert into Orders(name, status, price, user_id) VALUES ('Apple','RECEIVED',220, 1);
insert into Orders(name, status, price, user_id) VALUES ('TobotX','PROCESSING',5000, 2);
insert into Orders(name, status, price, user_id) VALUES ('Swimsuit','PROCESSING',7000, 3);